from django.core.management.base import BaseCommand
from game.models import Room, Question


QUESTIONS = {
    'Infrastructure & Cloud': {
        'description': 'How systems are built, scaled, and managed in the cloud',
        'easy': [
            {'text': 'What is the primary purpose of a cloud computing platform?', 'option_a': 'To provide on-demand access to computing resources over the internet without managing physical hardware', 'option_b': 'To replace local area networks with faster internet connections for office buildings', 'option_c': 'To store only backup copies of data that is already held on local servers', 'option_d': 'To provide a graphical interface for managing virtual machines on a single server', 'correct_answer': 'a'},
            {'text': 'What does Infrastructure as Code mean?', 'option_a': 'Writing application code that automatically scales based on server load and traffic patterns', 'option_b': 'Managing and provisioning infrastructure through machine-readable configuration files rather than manual processes', 'option_c': 'Using code comments to document the physical layout of data center infrastructure', 'option_d': 'Converting legacy infrastructure diagrams into executable scripts for documentation', 'correct_answer': 'b'},
            {'text': 'What is a virtual machine?', 'option_a': 'A software emulation of a physical computer that runs an operating system and applications in isolation', 'option_b': 'A physical server that has been optimized to run multiple applications simultaneously', 'option_c': 'A network device that routes traffic between different physical servers in a data center', 'option_d': 'A container that shares the host operating system kernel with other running processes', 'correct_answer': 'a'},
            {'text': 'What is horizontal scaling?', 'option_a': 'Increasing the CPU and memory of an existing server to handle more load', 'option_b': 'Adding more instances of a service to distribute load across multiple servers', 'option_c': 'Expanding the storage capacity of a single database server to hold more data', 'option_d': 'Upgrading network bandwidth between servers to reduce latency and improve throughput', 'correct_answer': 'b'},
            {'text': 'What is vertical scaling?', 'option_a': 'Adding more servers to a cluster to distribute workload across multiple instances', 'option_b': 'Deploying services across multiple geographic regions to reduce user latency', 'option_c': 'Increasing the resources of an existing server such as CPU, RAM, or storage', 'option_d': 'Splitting a monolithic application into smaller services that scale independently', 'correct_answer': 'c'},
            {'text': 'What is a load balancer?', 'option_a': 'A tool that monitors CPU usage and automatically restarts services that consume too many resources', 'option_b': 'A device or service that distributes incoming network traffic across multiple backend servers', 'option_c': 'A database component that balances read and write operations across multiple replicas', 'option_d': 'A scheduling algorithm that assigns tasks to workers based on their current processing capacity', 'correct_answer': 'b'},
            {'text': 'What is a region in cloud computing?', 'option_a': 'A single physical data center that hosts all services for a specific customer account', 'option_b': 'A logical grouping of resources based on their cost and performance characteristics', 'option_c': 'A geographic area containing multiple isolated data center locations called availability zones', 'option_d': 'A network boundary that separates production resources from development environments', 'correct_answer': 'c'},
            {'text': 'What is a CDN?', 'option_a': 'A centralized database network that stores application state across multiple cloud regions', 'option_b': 'A content delivery network that caches content at edge locations close to users globally', 'option_c': 'A continuous deployment network that automates code releases to production servers', 'option_d': 'A cloud DNS network that resolves domain names faster than traditional DNS servers', 'correct_answer': 'b'},
            {'text': 'What is auto scaling?', 'option_a': 'Automatically upgrading server operating systems and software packages during maintenance windows', 'option_b': 'Dynamically adjusting the number of running instances based on current demand and metrics', 'option_c': 'Automatically backing up data to multiple regions when storage capacity reaches a threshold', 'option_d': 'Scaling database connections automatically when application traffic increases beyond normal levels', 'correct_answer': 'b'},
            {'text': 'What is a managed service in cloud computing?', 'option_a': 'A cloud service where the provider handles infrastructure management, patching, and operations', 'option_b': 'A service that requires a dedicated team of engineers to manage all configurations manually', 'option_c': 'A service contract that guarantees 24/7 human support for all technical issues', 'option_d': 'A cloud resource that can only be accessed through the provider management console', 'correct_answer': 'a'},
        ],
        'hard': [
            {'text': 'What is the CAP theorem?', 'option_a': 'A theorem stating systems can optimize for cost, availability, and performance simultaneously', 'option_b': 'A principle that distributed systems must choose between consistency, availability, and partition tolerance', 'option_c': 'A rule that cloud systems can achieve capacity, accuracy, and performance as separate goals', 'option_d': 'A theorem that distributed databases can be consistent, available, and persistent at the same time', 'correct_answer': 'b'},
            {'text': 'What is infrastructure idempotency?', 'option_a': 'The ability to run the same provisioning script multiple times and always get the same result', 'option_b': 'The practice of deploying identical infrastructure in multiple cloud regions simultaneously', 'option_c': 'Ensuring all infrastructure changes are reversible and can be rolled back safely', 'option_d': 'The capability of infrastructure to automatically recover from failures without intervention', 'correct_answer': 'a'},
            {'text': 'What is chaos engineering?', 'option_a': 'A methodology for managing unplanned infrastructure changes in production environments', 'option_b': 'A practice of deliberately injecting failures into systems to identify weaknesses before they cause outages', 'option_c': 'A deployment approach that introduces randomness to prevent predictable failure patterns', 'option_d': 'A testing framework that simulates peak load conditions to verify auto-scaling behavior', 'correct_answer': 'b'},
            {'text': 'What is the difference between active-active and active-passive high availability?', 'option_a': 'Active-active uses two identical regions while active-passive uses one primary and one backup region', 'option_b': 'Active-active has all nodes handling traffic simultaneously while active-passive has a standby ready to take over', 'option_c': 'Active-active is more expensive but less reliable than active-passive for critical workloads', 'option_d': 'Active-passive synchronizes data in real time while active-active uses eventual consistency', 'correct_answer': 'b'},
            {'text': 'What is a service mesh?', 'option_a': 'A cloud networking layer that connects microservices using virtual network interfaces', 'option_b': 'A dedicated infrastructure layer handling service-to-service communication with observability and security', 'option_c': 'A load balancing solution that routes traffic between services based on health checks', 'option_d': 'A configuration management tool that synchronizes settings across microservice deployments', 'correct_answer': 'b'},
            {'text': 'What is eventual consistency in distributed systems?', 'option_a': 'A guarantee that all writes to a distributed system are immediately visible to all readers', 'option_b': 'A consistency model where replicas may temporarily diverge but will converge to the same state over time', 'option_c': 'A database property ensuring transactions are atomic even across multiple distributed nodes', 'option_d': 'A replication strategy that synchronizes all nodes before acknowledging a write operation', 'correct_answer': 'b'},
            {'text': 'What is a circuit breaker pattern?', 'option_a': 'A hardware component that protects cloud data centers from electrical surges', 'option_b': 'A pattern that stops sending requests to a failing service to allow it to recover', 'option_c': 'A network configuration that isolates failing nodes from the rest of the cluster', 'option_d': 'An auto-scaling trigger that breaks the connection between instances when load exceeds limits', 'correct_answer': 'b'},
            {'text': 'What is the difference between spot instances and reserved instances?', 'option_a': 'Spot instances offer a discount for paying upfront while reserved instances use spare capacity', 'option_b': 'Reserved instances are prepaid for 1-3 years at a discount while spot instances use spare capacity at lower cost but can be interrupted', 'option_c': 'Spot instances run in specific availability zones while reserved instances run anywhere', 'option_d': 'Reserved instances have better performance than spot instances due to dedicated hardware', 'correct_answer': 'b'},
            {'text': 'What is GitOps?', 'option_a': 'A Git workflow that requires all code changes to be approved by operations team members', 'option_b': 'Using Git as the single source of truth for infrastructure and application deployments', 'option_c': 'A set of Git best practices for managing infrastructure repositories with multiple contributors', 'option_d': 'An integration between Git and cloud providers to automatically provision new accounts', 'correct_answer': 'b'},
            {'text': 'What is the twelve-factor app methodology?', 'option_a': 'A software development guide describing twelve security controls for cloud applications', 'option_b': 'A set of best practices for building scalable, maintainable, and portable cloud-native applications', 'option_c': 'A compliance framework with twelve requirements for storing data in cloud environments', 'option_d': 'A deployment checklist with twelve steps for migrating applications to the cloud', 'correct_answer': 'b'},
        ],
    },
    'Security & Defense': {
        'description': 'Encryption, authentication, authorization, attack vectors, and defense strategies',
        'easy': [
            {'text': 'What is the difference between authentication and authorization?', 'option_a': 'Authentication grants access to resources while authorization verifies identity credentials', 'option_b': 'Authentication verifies who you are while authorization determines what you are allowed to do', 'option_c': 'Authentication encrypts data while authorization decrypts it for authorized users', 'option_d': 'Authorization happens before authentication in modern security frameworks', 'correct_answer': 'b'},
            {'text': 'What is multi-factor authentication?', 'option_a': 'Using multiple passwords that must all be entered correctly to gain access', 'option_b': 'An authentication method requiring two or more verification factors from different categories', 'option_c': 'A system that requires multiple administrators to approve access requests', 'option_d': 'Authentication that works across multiple cloud providers using a single identity', 'correct_answer': 'b'},
            {'text': 'What does the principle of least privilege mean?', 'option_a': 'Granting all users administrator access to prevent workflow disruptions', 'option_b': 'Users and services should only have the minimum permissions required to perform their tasks', 'option_c': 'Privileged users receive priority support and faster access to cloud resources', 'option_d': 'Access levels are determined by the seniority and tenure of team members', 'correct_answer': 'b'},
            {'text': 'What is encryption at rest?', 'option_a': 'Encrypting data while it is being transmitted between two network endpoints', 'option_b': 'A security protocol that encrypts connections during periods of low server activity', 'option_c': 'Encrypting stored data on disk so it cannot be read without the decryption key', 'option_d': 'Encrypting application memory to prevent other processes from reading sensitive data', 'correct_answer': 'c'},
            {'text': 'What is SQL injection?', 'option_a': 'A performance optimization technique for inserting data into databases faster', 'option_b': 'A security vulnerability where untrusted input is inserted into SQL queries causing unintended execution', 'option_c': 'A database migration tool that injects SQL scripts into new database schemas', 'option_d': 'A testing technique that inserts test data into databases to verify query performance', 'correct_answer': 'b'},
            {'text': 'What is cross-site scripting XSS?', 'option_a': 'A technique for sharing scripts between websites to reduce code duplication', 'option_b': 'A vulnerability where attackers inject malicious scripts into web pages viewed by other users', 'option_c': 'A method for running server-side scripts in client browsers for faster rendering', 'option_d': 'A cross-origin policy that prevents scripts from accessing resources on different domains', 'correct_answer': 'b'},
            {'text': 'What is a denial of service attack?', 'option_a': 'An attack that steals credentials by tricking users into entering them on fake login pages', 'option_b': 'An attack that overwhelms a system with traffic or requests making it unavailable to users', 'option_c': 'An attack that denies specific users access by modifying their permission settings', 'option_d': 'A social engineering attack that convinces administrators to deny access to systems', 'correct_answer': 'b'},
            {'text': 'What is zero trust security?', 'option_a': 'A model where no external traffic is trusted regardless of its source or destination', 'option_b': 'Never implicitly trusting any user or device regardless of network location and always verifying', 'option_c': 'A security framework with zero tolerance for policy violations regardless of severity', 'option_d': 'A compliance model where zero vulnerabilities are acceptable in production systems', 'correct_answer': 'b'},
            {'text': 'What is defense in depth?', 'option_a': 'Investing heavily in a single best-in-class security solution for maximum protection', 'option_b': 'Layering multiple security controls so failure of one does not compromise the entire system', 'option_c': 'Protecting only the most valuable assets with deep security while leaving others unguarded', 'option_d': 'Conducting deep security reviews of code changes before they reach production', 'correct_answer': 'b'},
            {'text': 'What is penetration testing?', 'option_a': 'Stress testing a system to determine its maximum capacity before it fails', 'option_b': 'An authorized simulated attack on a system to evaluate its security posture', 'option_c': 'Automated vulnerability scanning that runs continuously in production environments', 'option_d': 'Testing network penetration speeds to ensure firewalls do not reduce performance', 'correct_answer': 'b'},
        ],
        'hard': [
            {'text': 'What is perfect forward secrecy?', 'option_a': 'A security property ensuring all connections use the same key so auditing is simpler', 'option_b': 'Using ephemeral session keys so compromising the long-term private key does not expose past sessions', 'option_c': 'A certificate property that prevents certificates from being used after their expiration date', 'option_d': 'A key rotation schedule that ensures encryption keys are changed before they can be cracked', 'correct_answer': 'b'},
            {'text': 'What is a supply chain attack?', 'option_a': 'An attack that disrupts the procurement process for hardware components in data centers', 'option_b': 'Compromising a target by attacking a dependency, build tool, or trusted third-party software', 'option_c': 'An attack sequence that follows a supply chain of escalating privileges to reach a target', 'option_d': 'An attack that corrupts data flowing through message queues in distributed systems', 'correct_answer': 'b'},
            {'text': 'What is SSRF?', 'option_a': 'Secure Server Request Forgery where attackers forge server identities in TLS handshakes', 'option_b': 'Server-Side Request Forgery where attackers trick servers into making requests to internal resources', 'option_c': 'Session State Request Forgery that hijacks authenticated sessions using forged cookies', 'option_d': 'Shared Secret Request Forgery that exploits API key sharing between microservices', 'correct_answer': 'b'},
            {'text': 'What is a rainbow table attack and how is it mitigated?', 'option_a': 'An attack using multiple colors of traffic to bypass rate limiting and is stopped by CAPTCHAs', 'option_b': 'Using precomputed hash tables to crack passwords and mitigated by salting hashes', 'option_c': 'A multi-vector attack combining several techniques and stopped by defense in depth', 'option_d': 'A statistical attack on encryption that is mitigated by using longer key lengths', 'correct_answer': 'b'},
            {'text': 'What is lateral movement in a cyberattack?', 'option_a': 'Expanding the attack surface by exploiting services on adjacent network segments', 'option_b': 'After initial compromise moving through the network to access additional systems and escalate privileges', 'option_c': 'Moving stolen data out of the network through encrypted side channels', 'option_d': 'Attacking multiple targets simultaneously across different geographic locations', 'correct_answer': 'b'},
            {'text': 'What is IMDSv2 and why was it introduced?', 'option_a': 'An improved IAM policy format that uses JSON schema version 2 for better validation', 'option_b': 'A session-oriented metadata service for EC2 that requires a token to prevent SSRF attacks', 'option_c': 'An improved DNS metadata protocol for service discovery in containerized environments', 'option_d': 'The second version of AWS instance monitoring that adds support for custom metrics', 'correct_answer': 'b'},
            {'text': 'What is threat modeling?', 'option_a': 'Building machine learning models to automatically detect security threats in log data', 'option_b': 'Identifying potential threats, attack vectors, and vulnerabilities in a system during design', 'option_c': 'Creating visual diagrams of the threat landscape to communicate risks to stakeholders', 'option_d': 'Modeling attacker behavior based on historical incident data to predict future attacks', 'correct_answer': 'b'},
            {'text': 'What is a confused deputy problem?', 'option_a': 'A security issue where an administrator accidentally grants too many permissions to a service', 'option_b': 'When a privileged program is tricked into misusing its authority on behalf of an attacker', 'option_c': 'A misconfiguration where multiple services share the same IAM role causing permission conflicts', 'option_d': 'A vulnerability where service accounts have different permissions across deployment environments', 'correct_answer': 'b'},
            {'text': 'What is the OWASP Top 10?', 'option_a': 'A ranking of the ten most expensive security breaches in the history of the internet', 'option_b': 'A regularly updated list of the ten most critical web application security risks', 'option_c': 'A set of ten mandatory security controls required for PCI DSS compliance', 'option_d': 'Ten security testing tools recommended for penetration testing web applications', 'correct_answer': 'b'},
            {'text': 'What is a red team exercise?', 'option_a': 'A regulatory compliance review performed by an external auditing team', 'option_b': 'A simulated attack conducted by security professionals to test an organization defenses', 'option_c': 'An internal security review where the team uses red markers to highlight vulnerabilities', 'option_d': 'A disaster recovery exercise that tests the ability to restore systems after a failure', 'correct_answer': 'b'},
        ],
    },
    'Networking & Protocols': {
        'description': 'How data moves across networks — TCP/IP, DNS, routing, and protocols',
        'easy': [
            {'text': 'What does the OSI model define?', 'option_a': 'The rules for assigning IP addresses to devices on a network', 'option_b': 'A conceptual framework describing how network communication is divided into seven layers', 'option_c': 'The physical standards for Ethernet cables and wireless network equipment', 'option_d': 'The protocols required to connect private networks to the public internet', 'correct_answer': 'b'},
            {'text': 'What is the purpose of DNS?', 'option_a': 'To encrypt network traffic between clients and servers using digital certificates', 'option_b': 'To assign IP addresses dynamically to devices when they join a network', 'option_c': 'To translate human-readable domain names into machine-readable IP addresses', 'option_d': 'To route network packets between different networks based on destination addresses', 'correct_answer': 'c'},
            {'text': 'What is the difference between TCP and UDP?', 'option_a': 'TCP is faster while UDP provides guaranteed delivery with error checking', 'option_b': 'UDP is connection-oriented while TCP sends packets without establishing a connection', 'option_c': 'TCP provides reliable ordered delivery while UDP is faster but does not guarantee delivery', 'option_d': 'TCP works on local networks while UDP is designed for long-distance internet traffic', 'correct_answer': 'c'},
            {'text': 'What does DHCP do?', 'option_a': 'Encrypts network traffic to prevent eavesdropping on local area networks', 'option_b': 'Resolves domain names to IP addresses for all devices on the network', 'option_c': 'Automatically assigns IP addresses and network configuration to devices', 'option_d': 'Routes traffic between different networks using dynamic routing protocols', 'correct_answer': 'c'},
            {'text': 'What is NAT?', 'option_a': 'Network Authentication Technology that verifies device identities before granting access', 'option_b': 'Network Address Translation that maps private IP addresses to public IP addresses', 'option_c': 'Network Allocation Table that tracks IP address assignments on a subnet', 'option_d': 'Network Analysis Tool that captures and examines packets on a network segment', 'correct_answer': 'b'},
            {'text': 'What does a router do?', 'option_a': 'Connects multiple devices within the same local network using MAC addresses', 'option_b': 'Filters network traffic based on port numbers and protocol types', 'option_c': 'Forwards network packets between different networks based on IP addresses', 'option_d': 'Assigns IP addresses to devices and manages network configuration', 'correct_answer': 'c'},
            {'text': 'What is the three-way TCP handshake?', 'option_a': 'A process where three routers verify a route is available before data transmission begins', 'option_b': 'SYN, SYN-ACK, ACK — the connection establishment process in TCP', 'option_c': 'A three-step authentication process used to secure TCP connections', 'option_d': 'The process of negotiating TCP window size using three rounds of messages', 'correct_answer': 'b'},
            {'text': 'What is CIDR notation?', 'option_a': 'A standard format for writing network device configuration files', 'option_b': 'A compact way to represent an IP address and its associated subnet mask', 'option_c': 'A naming convention for identifying network interfaces on Linux systems', 'option_d': 'A compression format for reducing the size of routing table entries', 'correct_answer': 'b'},
            {'text': 'What is a private IP address range?', 'option_a': 'IP addresses assigned by IANA specifically to government and military organizations', 'option_b': 'IP addresses reserved for use on internal networks not routable on the public internet', 'option_c': 'IP addresses purchased privately from ISPs for exclusive use by one organization', 'option_d': 'IP addresses that are hidden from public DNS servers to prevent scanning attacks', 'correct_answer': 'b'},
            {'text': 'What is a VLAN?', 'option_a': 'A virtual local area network that segments a physical network into logical networks', 'option_b': 'A very large area network that connects devices across multiple geographic regions', 'option_c': 'A virtual link aggregation network that combines multiple physical links', 'option_d': 'A validated LAN that meets security standards for enterprise environments', 'correct_answer': 'a'},
        ],
        'hard': [
            {'text': 'What is anycast routing?', 'option_a': 'A routing method that sends packets to any available path regardless of destination', 'option_b': 'Routing where the same IP is announced from multiple locations and traffic goes to the nearest', 'option_c': 'A multicast routing protocol that sends packets to any subset of network nodes', 'option_d': 'A routing technique that allows any router to forward packets to any destination', 'correct_answer': 'b'},
            {'text': 'What is PMTUD and why can it fail?', 'option_a': 'Packet Management Traffic Unit Discovery that fails when routers drop large packets', 'option_b': 'Path MTU Discovery that can fail when ICMP type 3 code 4 messages are blocked by firewalls', 'option_c': 'Protocol Monitoring Traffic Unit Detection that fails due to incorrect subnet configurations', 'option_d': 'Private MTU Discovery that fails when routers do not support jumbo frame negotiation', 'correct_answer': 'b'},
            {'text': 'What is the difference between stateful and stateless firewalls?', 'option_a': 'Stateful firewalls inspect packet headers while stateless firewalls inspect payload content', 'option_b': 'Stateful firewalls track connection state while stateless firewalls evaluate each packet independently', 'option_c': 'Stateless firewalls are more secure because they do not maintain connection tracking tables', 'option_d': 'Stateful firewalls operate at Layer 3 while stateless firewalls operate at Layer 7', 'correct_answer': 'b'},
            {'text': 'What is TCP selective acknowledgment SACK?', 'option_a': 'A mechanism where the receiver acknowledges every other segment to reduce ACK traffic', 'option_b': 'An extension that allows receivers to acknowledge non-contiguous blocks so only missing segments are retransmitted', 'option_c': 'A selective acknowledgment that only confirms receipt of priority packets in a stream', 'option_d': 'A security mechanism that selectively authenticates TCP packets to prevent spoofing', 'correct_answer': 'b'},
            {'text': 'What is split horizon in distance vector routing?', 'option_a': 'Splitting routing tables between primary and backup routers for redundancy', 'option_b': 'A rule preventing a router from advertising a route back out the same interface it was learned from', 'option_c': 'Dividing routing domains at network boundaries to prevent routing loops', 'option_d': 'A technique that splits the network horizon view between different routing protocols', 'correct_answer': 'b'},
            {'text': 'What is OSPF and how does it differ from BGP?', 'option_a': 'OSPF is a distance vector protocol while BGP is a link-state protocol used for internal routing', 'option_b': 'OSPF is a link-state IGP for internal routing while BGP is a path vector EGP for inter-domain routing', 'option_c': 'OSPF routes based on bandwidth while BGP routes based on hop count between destinations', 'option_d': 'OSPF is used for internet routing while BGP is used for enterprise internal networks', 'correct_answer': 'b'},
            {'text': 'What is GRE tunneling?', 'option_a': 'Guaranteed Reliable Encryption tunneling that provides authenticated encrypted connections', 'option_b': 'Generic Routing Encapsulation that wraps packets from one protocol inside another protocol', 'option_c': 'Global Routing Exchange tunneling for connecting cloud regions over dedicated links', 'option_d': 'Group Relay Encapsulation for multicast traffic distribution across WAN networks', 'correct_answer': 'b'},
            {'text': 'What is a network namespace in Linux?', 'option_a': 'A naming convention for organizing network interfaces by their function and location', 'option_b': 'An isolated network stack with its own interfaces, routing tables, and firewall rules', 'option_c': 'A DNS namespace that separates internal and external domain name resolution', 'option_d': 'A virtual network segment created by a switch for isolating broadcast domains', 'correct_answer': 'b'},
            {'text': 'What is VxLAN?', 'option_a': 'Virtual eXtended LAN that extends Layer 2 networks across Layer 3 infrastructure using UDP encapsulation', 'option_b': 'Variable eXtension LAN that adds flexible addressing to traditional Ethernet networks', 'option_c': 'Virtualized eXternal LAN connecting on-premises networks to cloud VPCs over the internet', 'option_d': 'Validated eXtended LAN providing authenticated connections between data centers', 'correct_answer': 'a'},
            {'text': 'What is DNSSEC?', 'option_a': 'DNS over HTTPS that encrypts DNS queries to prevent interception by third parties', 'option_b': 'A suite of extensions adding cryptographic authentication to DNS responses', 'option_c': 'A secure DNS protocol that uses VPN tunnels to protect DNS traffic', 'option_d': 'DNS Security Center a centralized logging service for DNS query analysis', 'correct_answer': 'b'},
        ],
    },
    'Containers & Orchestration': {
        'description': 'How applications are packaged, deployed, and managed using containers',
        'easy': [
            {'text': 'What is a container?', 'option_a': 'A virtual machine that includes its own operating system kernel and hardware emulation', 'option_b': 'A lightweight isolated environment that packages an application with its dependencies', 'option_c': 'A physical server dedicated to running a single application in isolation', 'option_d': 'A cloud storage unit that holds application code and configuration files', 'correct_answer': 'b'},
            {'text': 'What is Kubernetes?', 'option_a': 'A container runtime that executes containers on a single server or virtual machine', 'option_b': 'An open-source system for automating deployment, scaling, and management of containers', 'option_c': 'A Docker alternative that provides simpler container management for small teams', 'option_d': 'A monitoring platform designed specifically for containerized workloads', 'correct_answer': 'b'},
            {'text': 'What is a pod in Kubernetes?', 'option_a': 'A group of worker nodes that share the same hardware configuration and resources', 'option_b': 'The smallest deployable unit containing one or more containers with shared networking', 'option_c': 'A Kubernetes namespace used to isolate workloads between different teams', 'option_d': 'A persistent storage volume attached to containers in a Kubernetes cluster', 'correct_answer': 'b'},
            {'text': 'What is a container registry?', 'option_a': 'A government database that tracks all containers deployed in public clouds', 'option_b': 'A compliance record of all containers running in production environments', 'option_c': 'A storage service for hosting and distributing container images', 'option_d': 'A container monitoring service that registers performance metrics centrally', 'correct_answer': 'c'},
            {'text': 'What is a Dockerfile?', 'option_a': 'A configuration file that defines how Docker should allocate resources to containers', 'option_b': 'A text file containing instructions for building a Docker container image', 'option_c': 'A network configuration file specifying how containers communicate with each other', 'option_d': 'A deployment manifest listing all containers to run in a production environment', 'correct_answer': 'b'},
            {'text': 'What is Docker Compose?', 'option_a': 'A tool for composing multiple Dockerfiles into a single optimized image', 'option_b': 'A software for managing Docker daemon configurations across multiple hosts', 'option_c': 'A tool for defining and running multi-container applications using a YAML file', 'option_d': 'A plugin that adds music playback capabilities to Docker container environments', 'correct_answer': 'c'},
            {'text': 'What is container orchestration?', 'option_a': 'Writing scripts that manually start and stop containers in a specific order', 'option_b': 'The automated management of container deployment, scaling, networking, and lifecycle', 'option_c': 'Coordinating container builds across multiple development environments simultaneously', 'option_d': 'Organizing containers into logical groups for billing and cost allocation purposes', 'correct_answer': 'b'},
            {'text': 'What is a Kubernetes deployment?', 'option_a': 'A process for manually installing Kubernetes on a cluster of bare metal servers', 'option_b': 'A Kubernetes resource that manages a set of pod replicas ensuring the desired count runs', 'option_c': 'A deployment pipeline that builds and releases containerized applications automatically', 'option_d': 'A record of all containers deployed to production in the past 30 days', 'correct_answer': 'b'},
            {'text': 'What is a Kubernetes service?', 'option_a': 'A managed cloud offering that runs Kubernetes without requiring cluster management', 'option_b': 'A microservice running inside a Kubernetes pod that handles a specific business function', 'option_c': 'A stable network endpoint that provides access to a set of pods', 'option_d': 'A background process running inside Kubernetes that manages cluster maintenance tasks', 'correct_answer': 'c'},
            {'text': 'What is a namespace in Kubernetes?', 'option_a': 'A naming standard for Kubernetes resources that ensures globally unique identifiers', 'option_b': 'A virtual cluster within a Kubernetes cluster for resource isolation between teams', 'option_c': 'A DNS namespace that provides service discovery within a Kubernetes cluster', 'option_d': 'A configuration namespace that separates development from production settings', 'correct_answer': 'b'},
        ],
        'hard': [
            {'text': 'What is the difference between a Deployment and a StatefulSet in Kubernetes?', 'option_a': 'Deployments are for stateless apps with interchangeable pods while StatefulSets provide stable identities and ordered operations', 'option_b': 'StatefulSets are newer and replace Deployments for all types of applications in modern Kubernetes', 'option_c': 'Deployments require persistent storage while StatefulSets are designed for ephemeral workloads', 'option_d': 'StatefulSets only support single replicas while Deployments support any number of replicas', 'correct_answer': 'a'},
            {'text': 'What is container escape?', 'option_a': 'The normal process of a container exiting when its main process finishes', 'option_b': 'A vulnerability that allows a process inside a container to access the host system', 'option_c': 'A technique for migrating a running container to a different host without downtime', 'option_d': 'Exiting a container shell session while leaving the container running', 'correct_answer': 'b'},
            {'text': 'What is the difference between liveness and readiness probes in Kubernetes?', 'option_a': 'Liveness probes check if a service is available while readiness probes check if it is running', 'option_b': 'Liveness probes restart containers that fail while readiness probes control traffic routing', 'option_c': 'Readiness probes are mandatory while liveness probes are optional performance checks', 'option_d': 'Liveness probes run at startup while readiness probes run continuously after startup', 'correct_answer': 'b'},
            {'text': 'What is a Kubernetes operator?', 'option_a': 'A Kubernetes administrator responsible for managing cluster operations', 'option_b': 'A method for encoding human operational knowledge as software using custom controllers', 'option_c': 'A Kubernetes role with permissions to operate all resources in the cluster', 'option_d': 'An automated process that operates cluster maintenance tasks like certificate rotation', 'correct_answer': 'b'},
            {'text': 'What is a Kubernetes admission controller?', 'option_a': 'A component that controls which administrators can access the Kubernetes API', 'option_b': 'A plugin that intercepts requests to the Kubernetes API to validate or mutate them', 'option_c': 'A rate limiter that controls how many resources can be admitted to the cluster per hour', 'option_d': 'A security gate that scans container images before admitting them to the cluster', 'correct_answer': 'b'},
            {'text': 'What is the container networking interface CNI?', 'option_a': 'A hardware interface card dedicated to container network traffic', 'option_b': 'A specification and libraries for configuring network interfaces in container runtimes', 'option_c': 'A network monitoring interface that captures all traffic between containers', 'option_d': 'A Kubernetes controller network interface for managing cluster networking', 'correct_answer': 'b'},
            {'text': 'What is etcd in Kubernetes?', 'option_a': 'A container runtime that executes pods on Kubernetes worker nodes', 'option_b': 'A distributed key-value store that holds all cluster state and configuration', 'option_c': 'A monitoring daemon that tracks the health of all containers in the cluster', 'option_d': 'A load balancer that distributes API server requests across the control plane', 'correct_answer': 'b'},
            {'text': 'What is a Kubernetes NetworkPolicy?', 'option_a': 'A company policy document defining acceptable use of Kubernetes in the organization', 'option_b': 'A specification controlling which pods can communicate with each other and external endpoints', 'option_c': 'A network performance policy that prioritizes traffic for critical Kubernetes services', 'option_d': 'A Kubernetes add-on that monitors network performance between pods', 'correct_answer': 'b'},
            {'text': 'What is a Kubernetes CRD?', 'option_a': 'Container Runtime Daemon the background process that manages container lifecycle', 'option_b': 'Custom Resource Definition extending the Kubernetes API with custom resource types', 'option_c': 'Cluster Resource Directory a catalog of all available resources in a cluster', 'option_d': 'Container Registry Driver a plugin for connecting to container registries', 'correct_answer': 'b'},
            {'text': 'What is image layer caching and why does layer order matter in Dockerfiles?', 'option_a': 'Layer caching stores images locally and order matters because larger layers should come first', 'option_b': 'Docker caches layers and invalidates cache from the changed layer down so stable layers should be first', 'option_c': 'Layer caching improves security and order matters because security layers must be last', 'option_d': 'Layers are cached by size so smaller layers should be at the bottom of the Dockerfile', 'correct_answer': 'b'},
        ],
    },
    'CI/CD & Automation': {
        'description': 'How code moves from development to production through automated pipelines',
        'easy': [
            {'text': 'What does CI stand for in CI/CD?', 'option_a': 'Container Integration the process of packaging applications into containers automatically', 'option_b': 'Continuous Integration frequently merging code changes and automatically building and testing them', 'option_c': 'Configuration Infrastructure automated management of server configuration files', 'option_d': 'Code Inspection automated review of code changes for quality and standards compliance', 'correct_answer': 'b'},
            {'text': 'What does CD stand for in CI/CD?', 'option_a': 'Continuous Deployment or Continuous Delivery automating the delivery of applications to production', 'option_b': 'Container Deployment using containers to deploy applications consistently', 'option_c': 'Code Distribution distributing compiled code artifacts to servers for execution', 'option_d': 'Cloud Deployment deploying applications specifically to cloud environments', 'correct_answer': 'a'},
            {'text': 'What is a build artifact?', 'option_a': 'A bug or defect introduced during the build process that needs to be fixed', 'option_b': 'The output of a build process such as a compiled binary, container image, or package', 'option_c': 'A historical record of all builds including their dates, durations, and outcomes', 'option_d': 'A configuration file generated during build that describes the application structure', 'correct_answer': 'b'},
            {'text': 'What is a pull request?', 'option_a': 'A request to pull the latest code changes from a remote repository to local machine', 'option_b': 'A mechanism for submitting contributions to a codebase for review and approval before merging', 'option_c': 'A deployment request that pulls a new container image to production servers', 'option_d': 'A request sent to the CI system to pull and run the latest test suite', 'correct_answer': 'b'},
            {'text': 'What is a staging environment?', 'option_a': 'An environment where developers write code before committing to version control', 'option_b': 'A pre-production environment that mirrors production used for final testing', 'option_c': 'A temporary environment created for each feature branch during development', 'option_d': 'An environment used by the sales team for product demonstrations to clients', 'correct_answer': 'b'},
            {'text': 'What is a GitHub Action?', 'option_a': 'A GitHub feature for creating and managing GitHub repositories programmatically', 'option_b': 'An automated workflow that runs on GitHub in response to repository events', 'option_c': 'A GitHub marketplace plugin that adds new features to repositories', 'option_d': 'An action taken by GitHub automatically when a repository violates policies', 'correct_answer': 'b'},
            {'text': 'What is test coverage?', 'option_a': 'The number of tests written for an application regardless of code execution', 'option_b': 'The percentage of source code exercised by automated tests', 'option_c': 'The range of environments in which tests are executed including local and CI', 'option_d': 'The coverage of business requirements by the test suite documentation', 'correct_answer': 'b'},
            {'text': 'What is a semantic version?', 'option_a': 'A version number assigned based on the semantic meaning and significance of the change', 'option_b': 'A versioning scheme using MAJOR.MINOR.PATCH to communicate the nature of changes', 'option_c': 'A version format that uses descriptive words instead of numbers for clarity', 'option_d': 'An automated versioning system that assigns version numbers based on commit messages', 'correct_answer': 'b'},
            {'text': 'What is GitOps?', 'option_a': 'A set of best practices for organizing Git repositories across large engineering teams', 'option_b': 'Using Git as the single source of truth for declarative infrastructure and application deployments', 'option_c': 'A Git workflow that integrates with ticketing systems for change management', 'option_d': 'An automated Git process that creates branches and pull requests on a schedule', 'correct_answer': 'b'},
            {'text': 'What is trunk-based development?', 'option_a': 'A Git branching strategy where every feature gets its own long-lived branch', 'option_b': 'Developers committing directly to or integrating frequently into a single main branch', 'option_c': 'A development approach where the trunk or database schema drives all design decisions', 'option_d': 'A workflow where code trunks from multiple repositories are merged periodically', 'correct_answer': 'b'},
        ],
        'hard': [
            {'text': 'What is the difference between continuous delivery and continuous deployment?', 'option_a': 'Continuous delivery is faster while continuous deployment requires more testing before release', 'option_b': 'Continuous delivery has a manual approval gate before production while continuous deployment deploys automatically', 'option_c': 'Continuous deployment is for applications while continuous delivery is for infrastructure changes', 'option_d': 'Continuous delivery deploys to staging while continuous deployment handles production releases', 'correct_answer': 'b'},
            {'text': 'What is OIDC federation in GitHub Actions with AWS?', 'option_a': 'A method for connecting GitHub organization accounts directly to AWS IAM user accounts', 'option_b': 'Allowing GitHub Actions to assume AWS IAM roles using temporary credentials without storing static keys', 'option_c': 'An Open ID Connect standard for federating GitHub accounts with AWS Cognito user pools', 'option_d': 'A federated identity system that syncs GitHub team membership with AWS IAM groups', 'correct_answer': 'b'},
            {'text': 'What is mutation testing?', 'option_a': 'Testing applications after making breaking changes to verify rollback procedures work', 'option_b': 'Introducing small code changes to verify tests detect them validating test quality', 'option_c': 'A testing approach that mutates test data to verify edge case handling', 'option_d': 'Testing container images after mutation to verify they maintain their intended behavior', 'correct_answer': 'b'},
            {'text': 'What is the four key DORA metrics?', 'option_a': 'Deployment frequency, lead time for changes, change failure rate, and time to restore service', 'option_b': 'Test coverage, build time, deployment success rate, and mean time between failures', 'option_c': 'Sprint velocity, code review time, release frequency, and incident response time', 'option_d': 'Commit frequency, pipeline duration, error rate, and infrastructure cost per deployment', 'correct_answer': 'a'},
            {'text': 'What is a canary analysis?', 'option_a': 'A security analysis that checks for canary tokens leaked in code or configuration', 'option_b': 'Automatically comparing metrics between canary and stable deployments to decide promotion', 'option_c': 'An analysis of canary deployment costs compared to full blue-green deployments', 'option_d': 'Manual review of canary deployment logs by an operator before promoting to production', 'correct_answer': 'b'},
            {'text': 'What is supply chain security in CI/CD?', 'option_a': 'Securing the physical supply chain of hardware used to build CI/CD infrastructure', 'option_b': 'Securing dependencies, build tools, and the pipeline itself to prevent supply chain attacks', 'option_c': 'Managing the supply of build agents to prevent pipeline queue starvation', 'option_d': 'A compliance framework for securing source code across the software supply chain', 'correct_answer': 'b'},
            {'text': 'What is an ephemeral environment?', 'option_a': 'A temporary cloud region that is created and destroyed based on demand', 'option_b': 'A short-lived environment created on demand for a specific purpose and destroyed after use', 'option_c': 'An environment that stores no persistent data and resets to defaults after each use', 'option_d': 'A staging environment that is periodically wiped and rebuilt from infrastructure code', 'correct_answer': 'b'},
            {'text': 'What is policy as code?', 'option_a': 'Writing policies in a programming language rather than natural language for clarity', 'option_b': 'Expressing compliance and governance policies as code that can be automatically enforced', 'option_c': 'Converting legal policies into code comments that document compliance requirements', 'option_d': 'A policy requiring all infrastructure to be defined in code before being deployed', 'correct_answer': 'b'},
            {'text': 'What is a flaky test?', 'option_a': 'A test that always fails because it is poorly written and needs to be fixed', 'option_b': 'A test that produces inconsistent results passing sometimes and failing others with the same code', 'option_c': 'A performance test that produces results that vary widely based on system load', 'option_d': 'A test that was once reliable but has been broken by a recent code change', 'correct_answer': 'b'},
            {'text': 'What is build provenance?', 'option_a': 'The geographic origin and build environment used to compile an application', 'option_b': 'Verifiable metadata about how a software artifact was built and from what source', 'option_c': 'The proven track record of a build pipeline demonstrated through historical metrics', 'option_d': 'Documentation proving that a build artifact is the original and has not been modified', 'correct_answer': 'b'},
        ],
    },
    'Observability & Reliability': {
        'description': 'Monitoring, logging, tracing, alerting, and keeping systems reliable',
        'easy': [
            {'text': 'What are the three pillars of observability?', 'option_a': 'Monitoring, alerting, and dashboards', 'option_b': 'Metrics, logs, and traces', 'option_c': 'CPU, memory, and network usage', 'option_d': 'Availability, performance, and security', 'correct_answer': 'b'},
            {'text': 'What is an SLA?', 'option_a': 'A software licensing agreement between a vendor and their enterprise customers', 'option_b': 'A Service Level Agreement a contract defining expected service availability and performance', 'option_c': 'A system log aggregator that collects and stores logs from multiple sources', 'option_d': 'A single log analysis platform for centralizing all application log data', 'correct_answer': 'b'},
            {'text': 'What is MTTR?', 'option_a': 'Maximum Time To Respond the longest acceptable time to respond to an incident', 'option_b': 'Mean Time To Restore the average time to recover a system after a failure', 'option_c': 'Minimum Time To Release the shortest time between software releases', 'option_d': 'Mean Traffic Transfer Rate the average bandwidth used by a service', 'correct_answer': 'b'},
            {'text': 'What is alert fatigue?', 'option_a': 'The degradation of alert accuracy over time as systems become more complex', 'option_b': 'When on-call engineers become desensitized to alerts due to excessive noise', 'option_c': 'The increased time required to acknowledge alerts as an engineer becomes tired', 'option_d': 'A monitoring problem where alerts are too infrequent to catch issues quickly', 'correct_answer': 'b'},
            {'text': 'What is structured logging?', 'option_a': 'Organizing log files in a structured directory hierarchy for easier retrieval', 'option_b': 'Writing logs in a consistent machine-readable format like JSON for better analysis', 'option_c': 'A logging approach that structures logs by severity from debug to critical', 'option_d': 'Compressing and archiving log files using a structured backup procedure', 'correct_answer': 'b'},
            {'text': 'What is a p99 latency metric?', 'option_a': 'The average latency across 99 percent of all requests served in a time period', 'option_b': 'The 99th percentile latency meaning 99 percent of requests are faster than this value', 'option_c': 'The latency measured when a service is running at 99 percent CPU utilization', 'option_d': 'A latency target specifying that 99 percent of requests must meet an SLO', 'correct_answer': 'b'},
            {'text': 'What is a post-mortem?', 'option_a': 'A review conducted before deployment to identify potential issues', 'option_b': 'An analysis conducted after an incident to understand what happened and prevent recurrence', 'option_c': 'A monitoring process that continues running after a service has been decommissioned', 'option_d': 'A final report written after a system is permanently shut down', 'correct_answer': 'b'},
            {'text': 'What is the golden signals approach to monitoring?', 'option_a': 'Using gold-standard industry metrics to benchmark systems against competitors', 'option_b': 'Monitoring latency, traffic, errors, and saturation as the four fundamental metrics', 'option_c': 'Sending golden path alerts to senior engineers when critical systems fail', 'option_d': 'A monitoring philosophy where only metrics with proven value are tracked', 'correct_answer': 'b'},
            {'text': 'What is on-call rotation?', 'option_a': 'Rotating engineers between different teams to share knowledge and avoid burnout', 'option_b': 'A schedule where engineers take turns being responsible for responding to incidents', 'option_c': 'A policy requiring engineers to be available for calls during business hours', 'option_d': 'A system that rotates on-call duties to the most senior engineer available', 'correct_answer': 'b'},
            {'text': 'What is synthetic monitoring?', 'option_a': 'Generating synthetic load to test how systems perform under pressure', 'option_b': 'Simulating user interactions to continuously test application functionality', 'option_c': 'Using artificial metrics derived from real metrics when direct measurement is difficult', 'option_d': 'Monitoring systems using synthetic data to avoid exposing real user data', 'correct_answer': 'b'},
        ],
        'hard': [
            {'text': 'What is an error budget?', 'option_a': 'A financial budget allocated for fixing bugs and security vulnerabilities', 'option_b': 'The allowed amount of unreliability derived from an SLO used to balance reliability and velocity', 'option_c': 'A budget for error monitoring tools and on-call compensation', 'option_d': 'The maximum number of errors permitted per day before an incident is declared', 'correct_answer': 'b'},
            {'text': 'What is the RED method in service monitoring?', 'option_a': 'Reliability, Efficiency, and Durability metrics for measuring long-term system health', 'option_b': 'Rate, Errors, and Duration the three key metrics for monitoring request-based services', 'option_c': 'Resilience, Elasticity, and Deployment metrics for DevOps pipeline performance', 'option_d': 'Requests, Events, and Data the three sources of observability signal', 'correct_answer': 'b'},
            {'text': 'What is OpenTelemetry?', 'option_a': 'An open-source telescope metaphor for looking at distributed system behavior', 'option_b': 'A vendor-neutral observability framework for instrumenting applications to generate metrics, logs, and traces', 'option_c': 'A telemetry protocol for transmitting satellite data to ground control stations', 'option_d': 'An open API standard for connecting different monitoring vendors together', 'correct_answer': 'b'},
            {'text': 'What is cardinality in metrics?', 'option_a': 'The total number of metrics collected by a monitoring system per second', 'option_b': 'The number of unique combinations of label values in a metric affecting storage and query performance', 'option_c': 'A measure of how critical a metric is for understanding system health', 'option_d': 'The direction a metric trend is moving indicating improvement or degradation', 'correct_answer': 'b'},
            {'text': 'What is tail-based sampling in distributed tracing?', 'option_a': 'Sampling the last few requests to a service to detect degradation before it peaks', 'option_b': 'Making sampling decisions at the end of a trace based on complete trace data', 'option_c': 'Collecting only the tail end of long traces to reduce storage requirements', 'option_d': 'A sampling strategy that drops traces below a minimum latency threshold', 'correct_answer': 'b'},
            {'text': 'What is chaos monkey?', 'option_a': 'A chaotic deployment tool that randomly selects deployment strategies', 'option_b': 'A tool that randomly terminates instances in production to test system resilience', 'option_c': 'A monitoring tool that randomly selects metrics to test alert configurations', 'option_d': 'A security tool that simulates monkey-in-the-middle attacks on running services', 'correct_answer': 'b'},
            {'text': 'What is toil in site reliability engineering?', 'option_a': 'Hard but valuable work that improves system reliability over time', 'option_b': 'Repetitive manual operational work that scales with service growth and provides no lasting value', 'option_c': 'The total oil and energy costs associated with running data center operations', 'option_d': 'Toil-free software that runs without requiring any operational intervention', 'correct_answer': 'b'},
            {'text': 'What is the USE method in resource monitoring?', 'option_a': 'Uptime, Speed, and Efficiency metrics for cloud cost optimization', 'option_b': 'Utilization, Saturation, and Errors metrics for every resource in a system', 'option_c': 'Usage, Scaling, and Events metrics for auto-scaling decisions', 'option_d': 'Uptime, SLA, and Error rate the three core reliability metrics', 'correct_answer': 'b'},
            {'text': 'What is a service level burn rate?', 'option_a': 'The rate at which cloud costs increase during high-traffic periods', 'option_b': 'How quickly the error budget is being consumed relative to the allowed rate', 'option_c': 'The rate at which SLA violations accumulate over a billing period', 'option_d': 'A metric showing how quickly service response times are degrading', 'correct_answer': 'b'},
            {'text': 'What is mean time between failures MTBF?', 'option_a': 'The average time between deploying changes and detecting their first failure', 'option_b': 'The average time a system operates between successive failures', 'option_c': 'The mean time required to bring backup systems online after a failure', 'option_d': 'The average time between when a failure occurs and when it is detected', 'correct_answer': 'b'},
        ],
    },
    'Databases & Storage': {
        'description': 'Relational and non-relational databases, storage, replication, and caching',
        'easy': [
            {'text': 'What is the difference between SQL and NoSQL databases?', 'option_a': 'SQL databases are faster while NoSQL databases support more complex queries', 'option_b': 'SQL databases use structured schemas and relational tables while NoSQL uses flexible schemas', 'option_c': 'NoSQL databases use the SQL query language while SQL databases use proprietary languages', 'option_d': 'SQL databases are cloud-only while NoSQL databases can run on-premises', 'correct_answer': 'b'},
            {'text': 'What is ACID in database transactions?', 'option_a': 'Automated Consistency In Databases a standard for database performance benchmarking', 'option_b': 'Atomicity, Consistency, Isolation, and Durability properties ensuring reliable transactions', 'option_c': 'Advanced Compliance Integrity Design a framework for database security compliance', 'option_d': 'Asynchronous Concurrent Incremental Delivery a database replication protocol', 'correct_answer': 'b'},
            {'text': 'What is database indexing?', 'option_a': 'Sorting database records in alphabetical order for faster sequential reading', 'option_b': 'A data structure that improves query performance by allowing fast lookup of records', 'option_c': 'Numbering database rows sequentially to track the order records were inserted', 'option_d': 'Creating a copy of the database organized differently to support reporting queries', 'correct_answer': 'b'},
            {'text': 'What is caching?', 'option_a': 'Compressing data to reduce storage costs on slower disk-based storage systems', 'option_b': 'Storing frequently accessed data in fast memory to reduce latency and database load', 'option_c': 'Backing up critical data to a secondary storage system for disaster recovery', 'option_d': 'A database optimization that converts slow disk reads to faster sequential scans', 'correct_answer': 'b'},
            {'text': 'What is database sharding?', 'option_a': 'Splitting database tables vertically by removing infrequently accessed columns', 'option_b': 'Horizontally partitioning data across multiple database instances by a shard key', 'option_c': 'Breaking a monolithic database into smaller microservices databases', 'option_d': 'Creating database shards from backup data for point-in-time recovery', 'correct_answer': 'b'},
            {'text': 'What is a read replica?', 'option_a': 'A database that accepts both read and write traffic as a replica of the primary', 'option_b': 'A copy of a database that accepts only read traffic offloading reads from the primary', 'option_c': 'A database copy that can be promoted to primary when the original fails', 'option_d': 'A cached copy of recent read queries stored in memory for fast retrieval', 'correct_answer': 'b'},
            {'text': 'What is connection pooling?', 'option_a': 'Grouping database connections by application for better resource allocation', 'option_b': 'Reusing a set of established database connections rather than creating a new one per request', 'option_c': 'Pooling multiple databases together to create a larger virtual database', 'option_d': 'A network configuration that routes database connections through a load balancer', 'correct_answer': 'b'},
            {'text': 'What is eventual consistency?', 'option_a': 'A guarantee that all writes are eventually stored permanently without loss', 'option_b': 'A model where replicas may temporarily diverge but will eventually converge to the same state', 'option_c': 'A consistency model where eventual performance improvements are guaranteed over time', 'option_d': 'A database property where all transactions eventually complete without deadlock', 'correct_answer': 'b'},
            {'text': 'What is a deadlock in databases?', 'option_a': 'A database state where all connections are in use and new requests are rejected', 'option_b': 'A situation where two transactions wait for each other to release locks causing a standstill', 'option_c': 'A dead connection that is no longer responsive but has not been cleaned up', 'option_d': 'A lock applied to a dead database record that cannot be updated', 'correct_answer': 'b'},
            {'text': 'What is WAL in database systems?', 'option_a': 'Wide Area Logging a protocol for writing logs to remote servers', 'option_b': 'Write-Ahead Logging recording changes before applying them enabling crash recovery', 'option_c': 'Web API Layer a standard for exposing database operations via HTTP', 'option_d': 'Write Audit Log a compliance feature recording all database write operations', 'correct_answer': 'b'},
        ],
        'hard': [
            {'text': 'What is MVCC in database systems?', 'option_a': 'Multi-Version Consistency Control that ensures all replicas have matching data', 'option_b': 'Multi-Version Concurrency Control that allows concurrent reads without blocking writes', 'option_c': 'Managed Version Control for Consistency that tracks all database schema changes', 'option_d': 'Maximum Version Concurrency Control that limits the number of simultaneous transactions', 'correct_answer': 'b'},
            {'text': 'What is a B-tree index and why is it commonly used?', 'option_a': 'A binary tree index that is commonly used because it supports only exact match queries', 'option_b': 'A balanced tree structure keeping data sorted enabling efficient search, insert, and range queries', 'option_c': 'A B-tree is commonly used because it stores data in blocks matching disk page sizes', 'option_d': 'A bidirectional tree that is commonly used because it supports both forward and backward scanning', 'correct_answer': 'b'},
            {'text': 'What is consistent hashing?', 'option_a': 'A hashing technique that consistently produces the same output for the same input', 'option_b': 'A technique that minimizes data movement when nodes are added or removed from a cluster', 'option_c': 'A consistent approach to database sharding that ensures equal data distribution', 'option_d': 'A hashing algorithm that provides consistent performance across all shard sizes', 'correct_answer': 'b'},
            {'text': 'What is a two-phase commit?', 'option_a': 'A database backup strategy that commits data in two phases for reliability', 'option_b': 'A distributed transaction protocol ensuring all participants commit or all rollback', 'option_c': 'A two-step commit process where code review precedes production database changes', 'option_d': 'A commit strategy that phases out old data while committing new data simultaneously', 'correct_answer': 'b'},
            {'text': 'What is the N+1 query problem?', 'option_a': 'A database problem where queries take N+1 milliseconds longer than acceptable', 'option_b': 'Executing N additional queries to fetch related data for each of N initial results', 'option_c': 'A problem where one extra database server is required for every N application servers', 'option_d': 'An indexing problem where N+1 indexes causes query performance degradation', 'correct_answer': 'b'},
            {'text': 'What is a LSM tree?', 'option_a': 'Large Scale Merge tree used in OLAP databases for fast analytical aggregations', 'option_b': 'Log-Structured Merge tree used in databases like Cassandra and RocksDB optimized for write-heavy workloads', 'option_c': 'Leaf-Sorted Memory tree used in in-memory databases for sub-millisecond access', 'option_d': 'Layered Storage Management tree used in cloud databases for tiered storage optimization', 'correct_answer': 'b'},
            {'text': 'What is the CAP theorem applied to databases?', 'option_a': 'Capacity, Availability, and Performance cannot be maximized simultaneously in any database', 'option_b': 'A distributed system can guarantee at most two of Consistency, Availability, and Partition Tolerance', 'option_c': 'Consistency, Atomicity, and Persistence are mutually exclusive in distributed systems', 'option_d': 'Cloud databases must choose between Cost, Availability, and Performance tradeoffs', 'correct_answer': 'b'},
            {'text': 'What is a CDC Change Data Capture system?', 'option_a': 'A Continuous Data Consolidation system that merges data from multiple databases', 'option_b': 'A system that tracks and captures every data change enabling streaming and replication', 'option_c': 'A Central Data Catalog that tracks the location and schema of all data assets', 'option_d': 'A Consistent Data Copy mechanism for creating synchronized database replicas', 'correct_answer': 'b'},
            {'text': 'What is the hot partition problem in distributed databases?', 'option_a': 'A partition that becomes too hot due to high CPU usage from complex queries', 'option_b': 'When one shard receives disproportionately more traffic than others due to skewed key distribution', 'option_c': 'A failed partition that is temporarily unavailable but continues to receive traffic', 'option_d': 'A partition corruption issue caused by writing too much data too quickly', 'correct_answer': 'b'},
            {'text': 'What is the difference between OLAP and OLTP databases?', 'option_a': 'OLAP is for transactional workloads while OLTP is optimized for analytical queries', 'option_b': 'OLTP is optimized for frequent transactions while OLAP is optimized for complex analytical queries', 'option_c': 'OLAP is a relational database while OLTP is a NoSQL database system', 'option_d': 'OLTP is for cloud databases while OLAP is for on-premises data warehouse systems', 'correct_answer': 'b'},
        ],
    },
    'Architecture & Design': {
        'description': 'System design patterns, scalability, microservices, and architectural trade-offs',
        'easy': [
            {'text': 'What is the difference between microservices and monolithic architecture?', 'option_a': 'Microservices use more servers while monolithic applications use fewer larger servers', 'option_b': 'A monolith is a single deployable unit while microservices decompose into independent services', 'option_c': 'Microservices are for startups while monolithic architecture is for large enterprises', 'option_d': 'Monolithic applications are faster but microservices are more secure', 'correct_answer': 'b'},
            {'text': 'What is an API gateway?', 'option_a': 'A physical gateway that controls access to the data center network', 'option_b': 'A server that acts as an entry point for clients managing routing, auth, and rate limiting', 'option_c': 'A software library that provides access to third-party APIs through a unified interface', 'option_d': 'A gateway that converts between different API protocols like REST and SOAP', 'correct_answer': 'b'},
            {'text': 'What is event-driven architecture?', 'option_a': 'An architecture where services communicate through scheduled batch events', 'option_b': 'An architecture where services communicate through producing and consuming events asynchronously', 'option_c': 'A design pattern where all business logic is triggered by user interface events', 'option_d': 'A system architecture driven by calendar events and scheduled maintenance windows', 'correct_answer': 'b'},
            {'text': 'What is loose coupling in system design?', 'option_a': 'Using lightweight protocols that create minimal coupling between services', 'option_b': 'Designing services to have minimal dependencies on each other enabling independent changes', 'option_c': 'A loose interpretation of coupling rules that allows some dependencies between services', 'option_d': 'Coupling services loosely using eventual consistency rather than strong consistency', 'correct_answer': 'b'},
            {'text': 'What is idempotency in API design?', 'option_a': 'The ability of an API to operate identically across all supported client types', 'option_b': 'An operation that produces the same result regardless of how many times it is called', 'option_c': 'An API design principle requiring identical request and response schemas', 'option_d': 'The property of APIs that maintain identity information across multiple calls', 'correct_answer': 'b'},
            {'text': 'What is fault tolerance?', 'option_a': 'A system tolerance for poor performance before triggering auto-scaling', 'option_b': 'The ability of a system to continue operating correctly despite component failures', 'option_c': 'The maximum number of faults a system can experience before requiring intervention', 'option_d': 'A monitoring tolerance threshold before triggering alerts and paging on-call', 'correct_answer': 'b'},
            {'text': 'What is graceful degradation?', 'option_a': 'A deployment strategy that gradually degrades the old version while the new one starts', 'option_b': 'The ability to maintain core functionality when components fail rather than complete failure', 'option_c': 'A scaling approach that gracefully reduces capacity during low-traffic periods', 'option_d': 'A database strategy that degrades to read-only mode when writes are unavailable', 'correct_answer': 'b'},
            {'text': 'What is domain-driven design?', 'option_a': 'Designing applications based on the domain name and URL structure they will use', 'option_b': 'A design approach where software structure reflects the business domain it serves', 'option_c': 'A design methodology driven by domain experts who create the application requirements', 'option_d': 'A cloud architecture pattern where each domain has its own cloud account', 'correct_answer': 'b'},
            {'text': 'What is the strangler fig pattern?', 'option_a': 'A security pattern that strangles unauthorized access attempts at the API gateway', 'option_b': 'Incrementally replacing a legacy system by routing features to new services piece by piece', 'option_c': 'A monitoring pattern that strangles noisy alerts by applying intelligent filtering', 'option_d': 'A deployment pattern that strangles traffic to the old version as confidence grows', 'correct_answer': 'b'},
            {'text': 'What is Conway law?', 'option_a': 'A law stating that system complexity grows proportionally to team size', 'option_b': 'Organizations design systems that mirror their own communication structure', 'option_c': 'A law governing data sovereignty that requires data to stay within national borders', 'option_d': 'A principle that Conway sequences must be followed when ordering microservices', 'correct_answer': 'b'},
        ],
        'hard': [
            {'text': 'What is event sourcing?', 'option_a': 'Tracking the source of events for audit and compliance purposes', 'option_b': 'Storing state as an immutable log of events and deriving current state by replaying them', 'option_c': 'Using external event sources like webhooks to trigger application workflows', 'option_d': 'Sourcing events from multiple producers into a centralized event stream', 'correct_answer': 'b'},
            {'text': 'What is CQRS?', 'option_a': 'Continuous Query and Response Synchronization for real-time data updates', 'option_b': 'Command Query Responsibility Segregation separating read and write models', 'option_c': 'Containerized Query and Resource Scaling for database performance optimization', 'option_d': 'Consistent Query and Replication Strategy for distributed database systems', 'correct_answer': 'b'},
            {'text': 'What is the difference between orchestration and choreography in microservices?', 'option_a': 'Orchestration is for containers while choreography is for serverless architectures', 'option_b': 'Orchestration has a central coordinator while choreography has services react to events independently', 'option_c': 'Choreography is more reliable than orchestration because it has no single point of failure', 'option_d': 'Orchestration is newer than choreography and is replacing it in modern architectures', 'correct_answer': 'b'},
            {'text': 'What is the outbox pattern?', 'option_a': 'A pattern for sending messages out of a system through an external message queue', 'option_b': 'Reliably publishing events by storing them in an outbox table in the same database transaction', 'option_c': 'A pattern for managing outbound messages that failed delivery for later retry', 'option_d': 'An architecture pattern where all outbound communication goes through a single gateway', 'correct_answer': 'b'},
            {'text': 'What is a shared-nothing architecture?', 'option_a': 'An architecture where services share nothing in common including their technology stack', 'option_b': 'Each node operates independently sharing no memory or disk with other nodes for linear scalability', 'option_c': 'An architecture with no shared state between users providing complete data isolation', 'option_d': 'A microservices pattern where services share nothing except a common database schema', 'correct_answer': 'b'},
            {'text': 'What is the actor model in concurrent systems?', 'option_a': 'A model where actors perform roles in a distributed system simulation', 'option_b': 'A computational model where actors are fundamental units that communicate only through messages', 'option_c': 'A concurrency model where actors take turns executing to prevent race conditions', 'option_d': 'A model where active components monitor passive components for state changes', 'correct_answer': 'b'},
            {'text': 'What is backpressure in streaming systems?', 'option_a': 'Network pressure that builds up when downstream bandwidth is less than upstream', 'option_b': 'A flow control mechanism where slow consumers signal producers to reduce send rate', 'option_c': 'Pressure applied to the back of a message queue to prioritize older messages', 'option_d': 'A monitoring metric measuring the build-up of unprocessed messages over time', 'correct_answer': 'b'},
            {'text': 'What is a data mesh architecture?', 'option_a': 'A mesh network of data centers connected for high-bandwidth data transfer', 'option_b': 'A distributed data ownership model where domain teams own their data as products', 'option_c': 'A mesh of caches distributed across a network for fast data access', 'option_d': 'An architecture that meshes multiple databases into a single queryable layer', 'correct_answer': 'b'},
            {'text': 'What is the thundering herd problem?', 'option_a': 'A problem where too many servers start simultaneously and solved by staggered startup', 'option_b': 'Many clients simultaneously requesting the same expired cache entry solved by cache locking or jitter', 'option_c': 'A database problem where many transactions compete for the same row lock simultaneously', 'option_d': 'A problem where many services discover a new service simultaneously overloading it', 'correct_answer': 'b'},
            {'text': 'What is a compensating transaction?', 'option_a': 'A transaction that compensates for poor database performance by reducing query complexity', 'option_b': 'An operation that semantically undoes the effects of a previous operation in a distributed system', 'option_c': 'A transaction with compensation logic that retries automatically on failure', 'option_d': 'A financial compensation paid to customers when a transaction failure causes data loss', 'correct_answer': 'b'},
        ],
    },
    'Linux & Systems': {
        'description': 'Linux fundamentals, shell, processes, filesystems, and system administration',
        'easy': [
            {'text': 'What does the ls command do?', 'option_a': 'Moves files from one location to another on the filesystem', 'option_b': 'Displays system resource usage including CPU and memory statistics', 'option_c': 'Lists the files and directories in the current or specified directory', 'option_d': 'Creates a new directory at the specified path on the filesystem', 'correct_answer': 'c'},
            {'text': 'What does chmod do?', 'option_a': 'Changes the owner of a file or directory to a specified user', 'option_b': 'Checks the current mode and permissions of a file on the filesystem', 'option_c': 'Changes the permissions of a file or directory on the filesystem', 'option_d': 'Creates a new mode for running applications in isolated environments', 'correct_answer': 'c'},
            {'text': 'What is a process in Linux?', 'option_a': 'A script that automates repetitive administrative tasks on a server', 'option_b': 'A running instance of a program with its own memory space and resources', 'option_c': 'A background service that starts automatically when the system boots', 'option_d': 'A scheduled job that runs at defined intervals using the cron daemon', 'correct_answer': 'b'},
            {'text': 'What does grep do?', 'option_a': 'Downloads files from the internet using HTTP or FTP protocols', 'option_b': 'Searches for patterns within files and outputs matching lines', 'option_c': 'Groups processes together for easier resource management and monitoring', 'option_d': 'Replaces text patterns in files with specified replacement strings', 'correct_answer': 'b'},
            {'text': 'What is sudo?', 'option_a': 'A command that switches the user account to a different user on the system', 'option_b': 'A tool that allows permitted users to run commands as another user typically root', 'option_c': 'A security daemon that monitors privileged command execution on the system', 'option_d': 'A super user domain that contains all administrative commands and utilities', 'correct_answer': 'b'},
            {'text': 'What is a daemon in Linux?', 'option_a': 'A process that consumes excessive system resources requiring intervention', 'option_b': 'A background process that runs continuously providing system services', 'option_c': 'A debugging utility that monitors system calls made by applications', 'option_d': 'A device driver that manages communication with hardware components', 'correct_answer': 'b'},
            {'text': 'What is a cron job?', 'option_a': 'A kernel job that runs at system startup to initialize hardware', 'option_b': 'A scheduled task that runs automatically at defined time intervals', 'option_c': 'A critical system job that runs with the highest scheduling priority', 'option_d': 'A cross-platform job runner that executes scripts on multiple servers', 'correct_answer': 'b'},
            {'text': 'What is a pipe in Linux?', 'option_a': 'A physical network pipe that carries data between servers in a data center', 'option_b': 'A mechanism connecting the output of one command to the input of another', 'option_c': 'A dedicated channel for inter-process communication using shared memory', 'option_d': 'A buffered connection between a process and a file on the filesystem', 'correct_answer': 'b'},
            {'text': 'What is the purpose of /dev/null?', 'option_a': 'A special file for storing null or empty configuration values', 'option_b': 'A special device that discards all data written to it', 'option_c': 'A development device used for testing without affecting production', 'option_d': 'A null pointer device used for initializing unset memory addresses', 'correct_answer': 'b'},
            {'text': 'What does chmod 755 mean?', 'option_a': 'Owner can read only, group can write, others can execute', 'option_b': 'Owner has all permissions, group and others can read and execute', 'option_c': 'Owner can execute, group can read, others have no permissions', 'option_d': 'All users have all permissions except write for group and others', 'correct_answer': 'b'},
        ],
        'hard': [
            {'text': 'What is the difference between a process and a thread?', 'option_a': 'Processes share memory with each other while threads have completely isolated memory', 'option_b': 'A process has its own memory space and resources while threads share memory within a process', 'option_c': 'Threads are heavier than processes and take longer to create and destroy', 'option_d': 'Processes are managed by the kernel while threads are managed by the application only', 'correct_answer': 'b'},
            {'text': 'What is the OOM killer in Linux?', 'option_a': 'A kernel feature that kills zombie processes that are out of memory', 'option_b': 'A kernel mechanism that terminates processes when the system runs out of memory', 'option_c': 'An out-of-memory monitor that alerts administrators before memory is exhausted', 'option_d': 'A process that kills other processes to free up out-of-memory conditions', 'correct_answer': 'b'},
            {'text': 'What is copy-on-write in Linux memory management?', 'option_a': 'Copying files to a write-protected backup before any modifications are made', 'option_b': 'Forked processes share memory pages until one writes and then a private copy is created', 'option_c': 'Writing data to a copy of the filesystem before applying changes to production', 'option_d': 'A memory protection technique that writes a copy of memory before releasing it', 'correct_answer': 'b'},
            {'text': 'What is a zombie process?', 'option_a': 'A process that consumes excessive CPU resources making the system unresponsive', 'option_b': 'A terminated process whose exit status has not yet been collected by the parent', 'option_c': 'A process that cannot be killed because it has locked critical system resources', 'option_d': 'A process that repeatedly restarts itself after being killed', 'correct_answer': 'b'},
            {'text': 'What is an inode?', 'option_a': 'An input node in the Linux networking stack for processing incoming packets', 'option_b': 'A data structure storing metadata about a file excluding its name and content', 'option_c': 'An index node in a B-tree filesystem index used for fast file lookups', 'option_d': 'An interface node connecting the filesystem to the block device layer', 'correct_answer': 'b'},
            {'text': 'What are Linux namespaces used for?', 'option_a': 'Providing namespace resolution for network services and DNS lookups', 'option_b': 'Isolating system resources so processes see different views of the system', 'option_c': 'Organizing system processes into namespaces for easier monitoring', 'option_d': 'Managing namespace collisions between processes using the same library names', 'correct_answer': 'b'},
            {'text': 'What are cgroups used for in Linux?', 'option_a': 'Grouping configuration files together for easier system administration', 'option_b': 'Limiting, accounting for, and isolating resource usage of process groups', 'option_c': 'Creating control groups of users with similar permission requirements', 'option_d': 'Grouping CPU cores together for dedicated allocation to specific workloads', 'correct_answer': 'b'},
            {'text': 'What is the difference between fork and exec system calls?', 'option_a': 'fork creates a new process by copying the parent while exec replaces the process image', 'option_b': 'exec creates a new process while fork replaces the current process with a new program', 'option_c': 'fork is used for threads while exec is used for processes in Linux systems', 'option_d': 'exec executes commands while fork forks the shell into a subshell', 'correct_answer': 'a'},
            {'text': 'What is the purpose of sysctl in Linux?', 'option_a': 'A system controller daemon that manages hardware device interactions', 'option_b': 'A tool for reading and modifying kernel parameters at runtime', 'option_c': 'A system control panel for managing running services and daemons', 'option_d': 'A controller for managing system-level containers and virtual machines', 'correct_answer': 'b'},
            {'text': 'What is address space layout randomization ASLR?', 'option_a': 'A memory layout algorithm that organizes address space for optimal cache usage', 'option_b': 'A security feature that randomizes memory address locations to prevent exploitation', 'option_c': 'A random layout of filesystem addresses to prevent fragmentation over time', 'option_d': 'An allocation strategy that randomly distributes memory across NUMA nodes', 'correct_answer': 'b'},
        ],
    },
    'APIs & Communication': {
        'description': 'REST, GraphQL, WebSockets, messaging, and how services communicate',
        'easy': [
            {'text': 'What does REST stand for?', 'option_a': 'Remote Execution Service Technology for running code on remote servers', 'option_b': 'Representational State Transfer an architectural style for web APIs', 'option_c': 'Real-time Event Streaming Technology for pushing data to clients', 'option_d': 'Resource Endpoint Service Template for defining API structures', 'correct_answer': 'b'},
            {'text': 'What is an HTTP status code 200?', 'option_a': 'The request was accepted and is being processed asynchronously', 'option_b': 'The request succeeded and the response contains the requested data', 'option_c': 'The resource was created successfully and is available at a new URL', 'option_d': 'The request was valid but the server has no content to return', 'correct_answer': 'b'},
            {'text': 'What does HTTP status code 404 mean?', 'option_a': 'The server encountered an error while processing the request', 'option_b': 'The request was unauthorized and requires valid authentication credentials', 'option_c': 'The requested resource was not found on the server', 'option_d': 'The server is temporarily unavailable due to maintenance or overload', 'correct_answer': 'c'},
            {'text': 'What is JSON?', 'option_a': 'JavaScript Object Notation a lightweight text format for data interchange', 'option_b': 'Java Serialization Object Notation for serializing Java objects to bytes', 'option_c': 'JavaScript Online Network a protocol for real-time browser communication', 'option_d': 'JSON is a programming language used for writing API backend services', 'correct_answer': 'a'},
            {'text': 'What is rate limiting in APIs?', 'option_a': 'Limiting the response payload size to improve API performance', 'option_b': 'Controlling the number of requests a client can make in a given time period', 'option_c': 'Limiting which API endpoints are accessible based on the client tier', 'option_d': 'A technique for reducing API latency by limiting processing overhead', 'correct_answer': 'b'},
            {'text': 'What is GraphQL?', 'option_a': 'A graph database query language for traversing connected data', 'option_b': 'A query language and runtime for APIs enabling clients to request exactly what they need', 'option_c': 'A graphic library for visualizing API data in charts and dashboards', 'option_d': 'A gradient optimization library used in machine learning API backends', 'correct_answer': 'b'},
            {'text': 'What is a WebSocket?', 'option_a': 'A web browser socket for connecting to local hardware like cameras', 'option_b': 'A full-duplex communication protocol over a single TCP connection', 'option_c': 'A socket.io library for managing real-time connections in Node.js', 'option_d': 'A web standard for secure encrypted HTTP connections', 'correct_answer': 'b'},
            {'text': 'What is gRPC?', 'option_a': 'A generic REST protocol checker for validating API implementations', 'option_b': 'A high-performance RPC framework using HTTP/2 and Protocol Buffers', 'option_c': 'A Google routing protocol for directing traffic between microservices', 'option_d': 'A general-purpose remote procedure call implementation for JavaScript', 'correct_answer': 'b'},
            {'text': 'What is a dead letter queue?', 'option_a': 'A queue that holds messages from terminated consumer processes', 'option_b': 'A queue where messages that cannot be processed successfully are stored', 'option_c': 'A deprecated queue that is no longer actively consumed by any service', 'option_d': 'A secure queue that permanently deletes messages after they are read', 'correct_answer': 'b'},
            {'text': 'What is the difference between synchronous and asynchronous API calls?', 'option_a': 'Synchronous APIs are faster while asynchronous APIs are more reliable', 'option_b': 'Synchronous calls wait for a response while async calls return immediately with a handle', 'option_c': 'Asynchronous APIs are synchronous with a delay for better performance', 'option_d': 'Synchronous APIs use HTTP while asynchronous APIs use message queues only', 'correct_answer': 'b'},
        ],
        'hard': [
            {'text': 'What is exactly-once delivery in messaging?', 'option_a': 'Guaranteeing messages are delivered at most once to prevent duplicate processing', 'option_b': 'Guaranteeing each message is processed exactly once despite retries and failures', 'option_c': 'A delivery guarantee where messages are exactly the size specified in the contract', 'option_d': 'Delivering exactly one message per second regardless of how many are queued', 'correct_answer': 'b'},
            {'text': 'What is the difference between at-least-once and at-most-once message delivery?', 'option_a': 'At-most-once is more reliable while at-least-once may cause message loss', 'option_b': 'At-least-once may duplicate messages but never loses them while at-most-once may lose messages but never duplicates', 'option_c': 'They provide identical guarantees but at-most-once uses more storage for deduplication', 'option_d': 'At-least-once is for critical messages while at-most-once is for non-critical messages', 'correct_answer': 'b'},
            {'text': 'What is backpressure in streaming systems?', 'option_a': 'Network pressure that builds up when downstream bandwidth is less than upstream', 'option_b': 'A flow control mechanism where slow consumers signal producers to reduce send rate', 'option_c': 'Pressure applied to the back of a message queue to prioritize older messages', 'option_d': 'A monitoring metric measuring the build-up of unprocessed messages over time', 'correct_answer': 'b'},
            {'text': 'What is the N+1 problem in GraphQL?', 'option_a': 'GraphQL schemas needing N+1 resolvers for every N types in the schema', 'option_b': 'Executing N additional database queries for each of N parent objects in a list', 'option_c': 'A GraphQL limitation where N fields require N+1 network roundtrips', 'option_d': 'A versioning problem where N+1 schema versions break backward compatibility', 'correct_answer': 'b'},
            {'text': 'What is the outbox pattern for reliable event publishing?', 'option_a': 'Publishing events out of a service through an external message broker reliably', 'option_b': 'Atomically writing events to an outbox table and separately publishing them to avoid dual-write problems', 'option_c': 'A pattern where outbound API calls are stored in an outbox for asynchronous delivery', 'option_d': 'Storing failed outbound messages in an outbox for manual retry by operators', 'correct_answer': 'b'},
            {'text': 'What is API deprecation?', 'option_a': 'Removing an API endpoint immediately when it is no longer needed', 'option_b': 'Signaling that an API version will be removed in the future giving clients time to migrate', 'option_c': 'Marking an API as deprecated when it has not been called in 30 days', 'option_d': 'A billing process that reduces API costs for endpoints with declining usage', 'correct_answer': 'b'},
            {'text': 'What is event streaming versus message queuing?', 'option_a': 'Event streaming is for real-time while message queuing is for batch processing only', 'option_b': 'Event streaming stores events for replay while message queuing delivers to one consumer and deletes', 'option_c': 'Message queuing supports more consumers simultaneously than event streaming platforms', 'option_d': 'They are equivalent technologies with different naming conventions', 'correct_answer': 'b'},
            {'text': 'What is hypermedia HATEOAS in REST APIs?', 'option_a': 'Using hyperlinks in API documentation to connect related endpoints', 'option_b': 'Including links in responses that guide clients on available next actions', 'option_c': 'Hyper-fast media delivery using CDNs optimized for REST API responses', 'option_d': 'A hypermedia protocol replacing JSON with a richer link-based format', 'correct_answer': 'b'},
            {'text': 'What is GraphQL federation?', 'option_a': 'Federating GraphQL schema changes across multiple development teams simultaneously', 'option_b': 'Composing multiple GraphQL services into a single unified graph schema', 'option_c': 'A federation of GraphQL servers that share a common schema registry', 'option_d': 'Using GraphQL to federate data across multiple geographic regions', 'correct_answer': 'b'},
            {'text': 'What is request hedging in distributed systems?', 'option_a': 'Hedging API bets by maintaining multiple competing implementations simultaneously', 'option_b': 'Sending duplicate requests to multiple backends and using the first response to reduce tail latency', 'option_c': 'A financial hedging strategy applied to API call costs in multi-cloud deployments', 'option_d': 'Sending requests through multiple network paths simultaneously for reliability', 'correct_answer': 'b'},
            {'text': 'What is semantic versioning and how should breaking API changes be handled?', 'option_a': 'Breaking changes increment the patch version while non-breaking changes use minor', 'option_b': 'Breaking changes require a major version increment giving clients time to migrate', 'option_c': 'All API changes regardless of impact should increment the version number', 'option_d': 'Breaking changes should be avoided entirely and never released to production', 'correct_answer': 'b'},
        ],
    },
}


class Command(BaseCommand):
    help = 'Seed the database with trivia rooms and questions'

    def handle(self, *args, **options):
        total_questions = 0

        for room_name, data in QUESTIONS.items():
            room, created = Room.objects.get_or_create(
                name=room_name,
                defaults={'description': data['description']}
            )
            if created:
                self.stdout.write(f'Created room: {room_name}')
            else:
                self.stdout.write(f'Room exists: {room_name}')

            for difficulty, questions in [('easy', data['easy']), ('hard', data['hard'])]:
                for q in questions:
                    _, created = Question.objects.get_or_create(
                        room=room,
                        text=q['text'],
                        difficulty=difficulty,
                        defaults={
                            'option_a': q['option_a'],
                            'option_b': q['option_b'],
                            'option_c': q['option_c'],
                            'option_d': q['option_d'],
                            'correct_answer': q['correct_answer'],
                        }
                    )
                    if created:
                        total_questions += 1

        self.stdout.write(
            self.style.SUCCESS(f'Done. {total_questions} new questions added across {len(QUESTIONS)} rooms.')
        )
